<<<<<<< HEAD
development:
  adapter: postgresql
  host: localhost
  database: "186"
  username: postgres
  password: postgres
  encoding: unicode
=======
development:
  adapter: postgresql
  host: localhost
  database: "186"
  username: postgres
  password: postgres
  encoding: unicode
>>>>>>> 060f5ed75711f821bc5fa8683a2ddf4d3f15a711
